Adding missing additional files

diff --git a/apt-backup b/apt-backup
--- a/apt-backup
+++ b/apt-backup
@@ -25,6 +25,16 @@
 #              |_lib/
 #
 #
+# VERIFY APT IS A PACKAGE MANAGER FOR OPERATING SYSTEM
+apt list ssh >&/dev/null
+if [ $? -ne 0 ]; then
+    echo "Could not verify 'apt' is your system's software manager."
+    echo "This script is for Debian-based Linux systems only."
+    echo "Exiting."
+    exit 0
+fi
+
+
 blue() { echo -en \033[36m; }
 red() { echo -en \033[31m; }
 white() { echo -en \033[00m; }
@@ -78,13 +88,18 @@ execute_sourcelist() {
 if [ -f "$sourcepath" ]; then
    echo -e "# **************************************************************************\n#"
    echo -e "# sources from ${sourcepath}\n#\t"
+   echo $sourcepath
+   unset count 
+   length=$(cat $sourcepath | wc -l)
    cat "$sourcepath" | while read -r line; do
+
       if [ "$line" == "" ] || [ $(echo "$line" | head -c 1) == "#" ]; then
          skip_this_line=true
       else
          echo -e "\t${line}"
       fi
-      if [ "$line" == "$(cat $sourcepath | tail -n 1)" ]; then
+      ((count++))
+      if [ "$count" == "$length" ]; then
          reached_end_of_file=true
          echo -e "\t<Reached end of file>\n"
       fi
@@ -101,16 +116,24 @@ execute_manuals() {
 }
 
 execute_ppa() {
+    unset count 
+
+
     if [ -d "$ppasources" ]; then
+       #length=$(ls -A1p | grep -v '\/' | wc -l)
+       
        echo -e "# **************************************************************************\n#"
        echo -e "# sources listed in ${ppasources}\n#"
-       if [ ! $(ls -1p "$ppasources" | grep -v '\/') ]; then
-            echo -e "#\tdirectory exists, but is empty\n#"
-       else
-            ls -1p "$ppasources" | grep -v '\/' | while read line; do
-            echo -e "\t$line"
+       if [ $(ls -1Ap "$ppasources" | grep -v '\/' | wc -l) -gt 0 ]; then
+            ls -1Ap "$ppasources" | grep -v '\/' | while read line; do
+               echo -e "\t$line"
+               #((count++))
             done
+
+       else
+            echo -e "#\tdirectory exists, but is empty\n#"
        fi
+    
     echo -e "\t<Reached end of file>\n"
     fi
 }
diff --git a/macc b/macc
--- a/macc
+++ b/macc
@@ -3,52 +3,117 @@
 #return current mac addresses of internet interfaces then
 #  change them to a random address from the same manufacturer
 
-echo 'Current mac-address assigned physical interfaces:'
-#macdump() { 
+
+
 #######################################
-
-ifexists() {
-hash $1
-if [ $? == 0 ]; then
-  echo $1 installed
-  else
-  echo Error. Please install $1 and retry
-  exit 1
-  fi
-}
-
-ifexists figlet
-ifexists macchanger
-#ifexists lkjslsss
+if [ "$SET_VARIABLES" == "true" ]; then
+   if [ -f $HOMEPATH/local/bin/ifexists ]; then
+      . ifexists rfkill
+      . ifexists ifconfig
+      . ifexists macchanger
+      . ifexists gcol
+   fi
+else
+   echo "Missing depends for the shell environment"
+   echo "Script may by wonky !"
+fi
 
 
-a=0
-b=$(ifconfig)
-t="/home/shawn/local/tmp/macc-tmp.txt"
-$null>"$t"
+
+if [ "$(rfkill list | grep 'yes')" ]; then
+   . gcol red
+   echo -n "WARNING: "
+   . gcol white
+   echo -e "rfkill shows interfaces \neither hard-blocked or soft-blocked."
+   echo "Script may not run as intended."
+   . gcol yellow
+   rfkill -r | column -t | grep 'DEVICE'
+   . gcol white
+   rfkill -r | column -t | grep -v 'DEVICE'
+   echo; read -p "(C)ontinue as is? (A)bort Command? or (U)nblock All?  C|A|U " yesno
+   case $yesno in
+     C|c)
+            echo -e "Proceeding with MacChanged as is\n"
+            ;;
+     A|a)
+            echo "Aborting..."
+            exit 0
+            ;;
+     U|u)
+            echo -e "Running 'rfkill unblock all'...\n"
+            rfkill unblock all
+            . gcol yellow
+            rfkill -r | column -t | grep 'DEVICE'
+            . gcol white
+            rfkill -r | column -t | grep -v 'DEVICE'
+            ;;
+      *)
+            echo "Invalid choice.  Aborting."
+            exit 0
+            ;;
+    esac
+   
+fi
+
 printlist() {
-echo "$b" | grep 'ether' | awk '{ print $2 }' | while read macadr;
-do
-ifadr=$(echo "$b" | grep -B 6 "$macadr" | grep 'flags' | awk '{ print $1 }' | sed 's/://g')
-echo -e "$ifadr\t $macadr" | tee -a "$t"
+#show current mac addresses for each interface
+ip -br a | awk '{ print $1 }' | while read line; do
+    . gcol navy
+    echo -e "Interface: $line"
+    . gcol white
+    macchanger -s $line 2>/dev/null | grep 'Current' | awk '{ print $1, " ", $2, " ", $3 }'
+   #macchanger -s $line 2>/dev/null | grep 'Current' | awk '{ printf $1; printf " "; printf $2; printf "  "; print $3 }'
+    if [ ! $? == 0 ]; then
+      "Could not return MAC Address."
+    fi
 done
 }
-#}
+
+
 #######################################
-figlet "start:"
-printlist
-figlet "authorizing"
+. gcol green
+echo -e "\nstart:"
+. gcol white
+printlist | column -t
+. gcol red
+echo -e "\nauthorizing..."
+. gcol white
 sudo echo ""
-figlet "spoofing..."
-cat $t | while read line; do
-ifa="$( echo $line | awk '{ print $1 }' )"
-echo ""; echo "Interface:    $ifa"
-sudo ifconfig "$ifa" down
-sudo macchanger -e "$ifa"
-sudo ifconfig "$ifa" up
+. gcol green
+echo -n "spoofing..."
+. gcol white
+
+spoofer() {
+ip -br a | awk '{ print $1 }' | while read line; do
+    . gcol yellow
+    echo -e "\nInterface:    $line"
+    . gcol white
+    sudo ifconfig "$line" down 2>/dev/null
+    unset previous_step
+    sudo macchanger -e $line 2>/dev/null | awk '{ print $1, " ", $2, " ", $3 }' | while read steps; do
+        if [ "$steps" == "Network didn't change" ]; then
+            . gcol red
+            # waiting for this error to pop back up so i can finish the script!!
+            echo "Error! Network didn't actually change the MAC address!"
+            . gcol white
+        else
+            echo "$steps"
+        fi
+    done
+    sudo ifconfig "$line" up 2>/dev/null
 done
-figlet "currently:"
-b=$(ifconfig)
-printlist
-figlet "MacChanged!"
+}
+
+spoofer | column -t
+. gcol green
+echo -e "\nNew Mac Address"
+. gcol white
+printlist | column -t
+. gcol blue
+echo "MACCHANGED!"
+echo -e "\n"
+. gcol white
+
 exit 0
+
+
diff --git a/vpnprep b/vpnprep
--- a/vpnprep
+++ b/vpnprep
@@ -1,69 +1,201 @@
 #!/bin/bash
 # vpnprep
-# ~/local/bin/vpnprep.d/vpnprep.conf
+# vpnprep downloads a csv file from vpngate.net, decodes configurations from base64,
+# and makes the fastest 3 entries into .ovpn files, then modifies them by adding
+# custom lines of code.  Existing vpns are removed from the OS, then the lastest
+# 6 ovpn configurations are added back into the OS.
 
+. ifexists curl
+. ifexists gcol
+. ifexists nmcli
 if [ ! $(uname -s) == "Linux" ]; then
    echo 'This program only works on linux machines.  No version for mac yet.'
    exit 0
 fi
-
-conf="$HOME/local/bin/vpnprep.d/vpnprep.conf"
-insert_flag='# The certificate file of the destination VPN Server.'
-uinpu="$*"
-
-id10tck() {
-echo 'This program adds lines network-manager-gnome needs to make vpngate.net config files to work'
-read -p 'Your file needs to be from vpngate.net.  Proceed? Y|n:? ' yesno
-case $yesno in
-    Y*|y*)
-        echo
-        ;;
-    *)
-        echo Aborting...
-        exit 0
-        ;;
-esac
+#prompt a passcode
+sudo echo -n
+download_vpn_file() {
+   mkdir -p ~/local
+   mkdir -p ~/local/tmp
+   . gcol yellow
+   echo "Downloading latest VPN configuration files..."
+   . gcol white
+   curl http://www.vpngate.net/api/iphone/ -o ~/local/tmp/vpngate.csv
+   error_flag=$?
+   if [ ${error_flag} != 0 ]; then
+      echo; . gcol red
+      echo "Error downloading CSV from vpngate.net."
+      echo "Error code from curl.  Aborting..."
+      . gcol white
+      exit 1
+   fi
 }
-# Uncomment for user confirmation
-#id10tck
+checksize() {
+   download_size=$(stat --printf="%s" ~/local/tmp/vpngate.csv)
+   if [ $download_size -lt 49999 ]; then
+      echo; . gcol red
+      echo "Error downloading CSV from vpngate.net."  
+      echo "Unexpected download size of ${download_size}.  Aborting..."
+      . gcol white
+      exit 1
+   fi
+}
+timestamp() {
+   date +"%B_%d"
+}
+prepfile() {
+   # ~/local/bin/vpnprep.d/vpnprep.conf
+   conf="$HOME/local/bin/vpnprep.d/vpnprep.conf"
+   insert_flag='# The certificate file of the destination VPN Server.'
+   target_ovpn_file="$*"
+   extension="$(echo "$target_ovpn_file" | tail -c 6)"
+   #echo "$extension"
+   if [ ! -f "$conf" ]; then
+      echo "No configuration file found."
+      echo "Expected to find a text file at ${conf}"
+      exit 2
+   elif [ ! "$extension" == ".ovpn" ]; then
+      echo Enter a .ovpn file to modify
+      exit 1
+   else
+      ready_to_cat=true
+   fi
 
-extension="$(echo "$uinpu" | tail -c 6)"
-#echo "$extension"
-if [ ! -f "$conf" ]; then
-    echo "No configuration file found"
-    exit 2
-elif [ ! "$extension" == ".ovpn" ]; then
-    echo Enter a .ovpn file to modify
-    exit 1
-else
-    ready_to_cat=true
-fi
+   modified_file=$(echo "$target_ovpn_file" | sed -E 's/\.ovpn$/-modified\.ovpn/g')
+   c=$(sed -n '/The\scertificate\sfile\sof\sthe\sdestination\sVPN\sServer/=' "$target_ovpn_file")
+   a=$(( $c - 3 ))
+   b=$(( $a + 1 ))
 
-modified_file=$(echo "$uinpu" | sed -E 's/\.ovpn$/-modified\.ovpn/g')
-c=$(sed -n '/The\scertificate\sfile\sof\sthe\sdestination\sVPN\sServer/=' "$uinpu")
-a=$(( $c - 3 ))
-b=$(( $a + 1 ))
-debug1() {
-echo $modified_file
-echo $uinpu
-echo a: $a b: $b
-echo $ready_to_cat
-echo $conf
-
-exit 0
+   head -n $a "$target_ovpn_file" > "$modified_file"
+   cat "$conf" >> "$modified_file"
+   tail -n +$b "$target_ovpn_file" >> "$modified_file"
+   . gcol blue
+   echo -n "Created " 
+   . gcol white
+   echo $modified_file
+#   . gcol white
 }
 
-head -n $a "$uinpu" | tee "$modified_file"
-cat "$conf" | tee -a "$modified_file"
-tail -n +$b "$uinpu" | tee -a "$modified_file"
+download_vpn_file
+checksize
+
+VPNCODE64=$(cat ~/local/tmp/vpngate.csv | awk -F ',' '{print $15}')
+echo "$VPNCODE64" > ~/local/tmp/vpngate.csv.64
+
+#define the array
+arr=()
+while IFS= read -r line; do
+   arr+=("$line")
+done < ~/local/tmp/vpngate.csv.64
+
+. gcol yellow
+echo "Creating VPN files..."
+. gcol white
+
+mkdir -p ~/vpn
+count=0
+seq 2 4 | while read line; do
+   ((count++))
+   filename=~/vpn/vpn_$(timestamp)_${count}.ovpn
+   echo -n ${arr[$line]} | base64 -d -i > ${filename}
+   . gcol navy
+   echo -n "Created "
+   . gcol white
+   echo $filename
+#   . gcol white
+   prepfile ${filename}
+done
+
+remove_vpns() {
+   vpn_count=0
+   nmcli connection show | sort -r | grep 'vpn' | while read -r line; do
+   ((vpn_count++))
+   if [ ${vpn_count} -gt 0 ]; then
+      connection_type=$(echo "${line}" | awk '{ print $3 }')
+      connection_id=$(echo "${line}" | awk '{ print $2 }')
+      connection_name=$(echo "${line}" | awk '{ print $1 }')
+      if [ "${connection_type}" == "vpn" ]; then
+         remove_profile=TRUE
+         sudo nmcli connection delete "${connection_id}" >/dev/null
+         . gcol red
+         echo -n "Deleted "
+         . gcol white
+         echo "${connection_id}"
+      fi
+   fi
+   done
+}
+
+add_latest_vpns() {
+   count=0
+   ls -1t $HOME/vpn | grep 'modified.ovpn' | while read -r line; do
+      ((count++))
+      if [ $count -gt 6 ]; then
+         break 2
+      else
+         sudo nmcli connection import type openvpn file $HOME/vpn/$line >/dev/null
+         . gcol green
+         echo -n "Added "
+         . gcol white
+         echo "${line}"
+      fi
+   done
+}
+connect_to_vpn() {
+echo;
+#connect to first profile
+   new_vpn_profile_list=$(ls -1t $HOME/vpn | grep 'modified.ovpn')
+   new_vpn_profile=$(echo "$new_vpn_profile_list" | head -n 3 | tail -n 1 | sed 's/.ovpn//g')
+   . gcol yellow
+   echo "Connecting to ${new_vpn_profile}"
+   sudo nmcli con up id "${new_vpn_profile}" >/dev/null
+#was it successful?   
+      erck=$?
+# if unsuccessful....
+      if [ $erck != 0 ]; then
+         . gcol red
+         echo "Connection to ${new_vpn_profile} failed."
+         . gcol yellow
+         new_vpn_profile=$(echo "$new_vpn_profile_list" | head -n 2 | tail -n 1 | sed 's/.ovpn//g')
+         echo "Connecting to ${new_vpn_profile}"
+         sudo nmcli con up id "${new_vpn_profile}" >/dev/null
+         erck=$?
+            if [ $erck != 0 ]; then
+             . gcol red
+               echo "Connection to ${new_vpn_profile} failed."
+               new_vpn_profile=$(echo "$new_vpn_profile_list" | head -n 1 | sed 's/.ovpn//g')
+               . gcol yellow
+               echo "Connecting to ${new_vpn_profile}"
+               sudo nmcli con up id "${new_vpn_profile}" >/dev/null
+               erck=$?
+                  if [ $erck == 0 ]; then
+                     . gcol green
+                     echo "Connection to ${new_vpn_profile} successful."
+                  else
+                     . gcol red
+                     echo "Connection to ${new_vpn_profile} failed.  Try manually.  Aborting."
+
+                  fi
+            else
+               . gcol green
+               echo "Connection to ${new_vpn_profile} successful."
+            fi
+   
+   else
+      . gcol green
+      echo "Connection to ${new_vpn_profile} successful."
+   fi
+}
+
+. gcol white
+remove_vpns
+add_latest_vpns
+connect_to_vpn
 
 
-echo -e "\n\nAdded configuration for Ubuntu.  Load Open VPN and test."
-
-exit 0
+echo
 
 
-# sed -n '/Databases/=' thegeekstuff.txt
-
-
+# these lines will now automatically import the new configuration files
+#sudo nmcli connection import type openvpn file **insert-file-here**
 
diff --git a/ytdl b/ytdl
--- a/ytdl
+++ b/ytdl
@@ -1,13 +1,72 @@
 #!/bin/bash
+# ytdl
+# shortcuts the YOUTUBE-DL command and creates a folder in ~/downloads/youtube-dl/{timestamp}
+
+#check to see if the right packages are installed
+. ifexists youtube-dl
+. ifexists figlet
+. ifexists gcol
+
+userinput="$1"
+#folderoption="$2"
+
 function fytdl() {
-mkdir -p ~/Downloads/youtube-dl
-spdir=$(date +"%H%M%S")
-mkdir -p ~/Downloads/youtube-dl/$spdir
-echo "YouTube-DL... syntax $ ytdl http://www.yourvideo.com/path/entered/here.html"
-echo "options -c, -i, and -format=best enabled."
-echo "Saving video to $HOME/Downloads/youtube-dl/$spdir"
-echo "Downloading video from $1"
-echo "Press ctrl+c to interrupt"
-youtube-dl -ci -f best $1 -o "$HOME/Downloads/youtube-dl/$spdir/%(title)s-%(id)s.%(ext)s"
+   mkdir -p ~/Downloads/youtube-dl
+   spdir=$(date +"%H%M%S")
+   mkdir -p ~/Downloads/youtube-dl/$spdir
+   echo "YouTube-DL... syntax $ ytdl http://www.yourvideo.com/path/entered/here.html"
+   echo "options -c, -i, and -format=best enabled."
+   . gcol yellow
+   echo "Saving video to $HOME/Downloads/youtube-dl/$spdir"
+   . gcol white
+   echo "Downloading video from $userinput"
+   echo "Press ctrl+c to interrupt"
+   youtube-dl -ci -f best "$1" -o "$HOME/Downloads/youtube-dl/$spdir/%(title)s-%(id)s.%(ext)s"
 }
-fytdl "$1"
+
+function fytdl_nodir() {
+   mkdir -p ~/Downloads/youtube-dl
+   echo "YouTube-DL... syntax $ ytdl http://www.yourvideo.com/path/entered/here.html"
+   echo "options -c, -i, and -format=best enabled."
+   . gcol yellow
+   echo "Saving video to $HOME/Downloads/youtube-dl"
+   . gcol white
+   echo "Downloading video from $userinput"
+   echo "Press ctrl+c to interrupt"
+   youtube-dl -ci -f best "$1" -o "$HOME/Downloads/youtube-dl/%(title)s-%(id)s.%(ext)s"
+}
+
+#read -p "Create a new folder the playlist or each URL?  Y|n: " folderoption
+fytdl "$userinput"
+. gcol yellow
+figlet 'downloaded'
+. gcol white
+
+exit 0
+
+      case ${folderoption} in
+            Y*|y*)
+                  . gcol red
+                  echo "Making new directories"
+                  . gcol white
+                  fytdl "$userinput"
+                  ;;
+#            N*|n*)
+             *)
+                  . gcol red
+                  echo "Skipping directory creation"
+                  . gcol white
+                  fytdl_nodir "$userinput"
+                  ;;
+#            *)
+#                  . gcol red
+#                  echo "error"
+#                  . gcol white
+#                  exit 1
+#                  ;;
+      esac
+
+. gcol yellow
+figlet 'downloaded'
+. gcol white
+
